replicaCount: 1

image:
  repository: mael0/overleaf-notifications
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3042

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
