replicaCount: 1

image:
  repository: mael0/redis
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  storageClass: "csi-sc-cinder"
  accessModes: ReadWriteOnce
  size: 1Gi
