apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-project-history
  labels:
    app: {{ .Release.Name }}-project-history
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-project-history
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-project-history
    spec:
      containers:
        - name: {{ .Release.Name }}-project-history
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-global-env