apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-docstore
  labels:
    app: {{ .Release.Name }}-docstore
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ .Release.Name }}-docstore
