# Becuase history-v1 seems to have hardcoded mongo host
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}

  selector:
    app: {{ .Release.Name }}-mongo
