apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mongo
  labels:
    app: {{ .Release.Name }}-mongo
spec:
  serviceName: mongo
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
        - name: {{ .Release.Name }}-mongo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
            - name: mongo-init-script
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: MONGO_INITDB_DATABASE
              value: "sharelatex"
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc-mongo
        - name: mongo-init-script
          configMap:
            name: {{ .Release.Name }}-mongo-configmap
