apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc-clsi-cache
spec:
  accessModes:
    - {{ .Values.persistence.clsiCache.accessModes | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.clsiCache.size }}
  storageClassName: {{ .Values.persistence.clsiCache.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc-clsi-output
spec:
  accessModes:
    - {{ .Values.persistence.clsiOutput.accessModes | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.clsiOutput.size }}
  storageClassName: {{ .Values.persistence.clsiOutput.storageClass }}
