replicaCount: 1

image:
  repository: mael0/overleaf-filestore
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3009

persistence:
  publicFiles:
    size: 1Gi
    accessModes: ReadWriteOnce
    className: csi-sc-cinder
  templateFiles:
    size: 1Gi
    accessModes: ReadWriteOnce
    className: csi-sc-cinder
  uploads:
    size: 1Gi
    accessModes: ReadWriteOnce
    className: csi-sc-cinder
  userFiles:
    size: 1Gi
    accessModes: ReadWriteOnce
    className: csi-sc-cinder

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
