replicaCount: 1

image:
  repository: mael0/overleaf-docstore
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3016

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
