apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv-filestore-public-files
spec:
  capacity:
    storage: {{ .Values.persistence.publicFiles.size }}
  accessModes:
    - {{ .Values.persistence.publicFiles.accessModes }}
  hostPath:
    path: /tmp/{{ .Release.Name }}-pv-filestore-public-files
  storageClassName:  {{ .Values.persistence.publicFiles.className }}
  claimRef:
    name: {{ .Release.Name }}-pvc-filestore-public-files
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv-filestore-template-files
spec:
  capacity:
    storage: {{ .Values.persistence.templateFiles.size }}
  accessModes:
    - {{ .Values.persistence.templateFiles.accessModes }}
  hostPath:
    path: /tmp/{{ .Release.Name }}-pv-filestore-template-files
  storageClassName: {{ .Values.persistence.templateFiles.className }}
  claimRef:
    name: {{ .Release.Name }}-pvc-filestore-template-files
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv-filestore-uploads
spec:
  capacity:
    storage: {{ .Values.persistence.uploads.size }}
  accessModes:
    - {{ .Values.persistence.uploads.accessModes }}
  hostPath:
    path: /tmp/{{ .Release.Name }}-pv-filestore-uploads
  storageClassName: {{ .Values.persistence.uploads.className }}
  claimRef:
    name: {{ .Release.Name }}-pvc-filestore-uploads
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv-filestore-user-files
spec:
  capacity:
    storage: {{ .Values.persistence.userFiles.size }}
  accessModes:
    - {{ .Values.persistence.userFiles.accessModes }}
  hostPath:
    path: /tmp/{{ .Release.Name }}-pv-filestore-user-files
  storageClassName: {{ .Values.persistence.userFiles.className }}
  claimRef:
    name: {{ .Release.Name }}-pvc-filestore-user-files
    namespace: {{ .Release.Namespace }}
