apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-filestore
  labels:
    app: {{ .Release.Name }}-filestore
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ .Release.Name }}-filestore
