replicaCount: 1

image:
  repository: mongo
  tag: "6.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  storageClass: "standard"
  accessModes: ReadWriteOnce
  size: 10Gi
