replicaCount: 1

image:
  repository: mael0/mongo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  storageClass: "csi-sc-cinder"
  accessModes: ReadWriteOnce
  size: 10Gi
