apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front
  labels:
    app: {{ .Release.Name }}-front
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      port: 80
      targetPort: 80
      nodePort: 30520
  selector:
    app: {{ .Release.Name }}-front
