replicaCount: 1

image:
  repository: mael0/overleaf-chat
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3010

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
